name: Make new release
on:
  workflow_dispatch:
    inputs:
        version_bump:
          description: 'New version:'
          required: true
          default: 'patch'
          type: choice
          options:
          - overwrite previous tag
          - minor
          - major
          - patch
jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Bump version
      shell: python
      env:
        VERSION_BUMP: ${{ inputs.version_bump }} 
      run: |
        from pathlib import Path
        import re
        import os
        v_file=Path("scripts","addons","cam","version.py")
        version_txt=v_file.read_text()
        major,minor,patch = re.match(r".*\((\d+),(\d+),(\d+)\)",version_txt).groups()
        major=int(major)
        minor=int(minor)
        patch=int(patch)
        bump = os.getenv("VERSION_BUMP")
        if bump == "minor":
          minor+=1
        if bump=='patch':
          patch+=1
        elif bump=='minor':
          minor+=1
          patch=0
        elif bump=='major':
          major+=1
          minor=0
          patch=0
        v_file.write_text(f"__version__={(major,minor,patch)}")
        env_file = Path(os.getenv('GITHUB_ENV'))  
        env_file.write_text(f"VERSION_TAG={major}.{minor}.{patch}")
        print(f"New version: {major}.{minor}.{patch}")
    - name: Make addon zip
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'blendercam.zip'
        directory: './scripts/addons'
    - name: Write version number
      run: |
        git config --global user.name 'Release robot'
        git config --global user.email 'release-robot@users.noreply.github.com'
        git commit -am "Version number"
        git tag -f ${{ env.VERSION_TAG }}
        git push
    - name: tag release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "scripts/addons/blendercam.zip"
        commit: ${{ env.VERSION_TAG }}

